### ISSUE TITLE
Make plugin available for self-hosted, non-composer instances

### ISSUE THREAD

**Issue by star26bsd** [auth0/wordpress#861]
Hi!

I was about to install your plugin on my self-hosted, non-composer WP instance. The activation fails.

Steps to reproduce:
- Login to WP backend => Plugins => Upload Plugin
- Upload Plugin, click install
- click 'active'

Error:
```
Warning: require_once(/home/.../public_html/dev.....ch/wp-content/plugins/wp-auth0-5.0.0/vendor/autoload.php): Failed to open stream: No such file or directory in /home/.../public_html/dev.....ch/wp-content/plugins/wp-auth0-5.0.0/wpAuth0.php on line 30

Fatal error: Uncaught Error: Failed opening required '/home/.../public_html/dev....ch/wp-content/plugins/wp-auth0-5.0.0/vendor/autoload.php' (include_path='.') in /home/.../public_html/dev....ch/wp-content/plugins/wp-auth0-5.0.0/wpAuth0.php:30 Stack trace: #0 /home/../public_html/dev....ch/wp-admin/includes/plugin.php(2314): include_once() #1 /home/.../public_html/dev.....ch/wp-admin/plugins.php(192): plugin_sandbox_scrape('wp-auth0-5.0.0/...') #2 {main} thrown in /home/.../public_html/dev.....ch/wp-content/plugins/wp-auth0-5.0.0/wpAuth0.php on line 30
```

Also, the Wordpress Plugin directory still shows the old plugin version, so users are forced to upload the plugin manually, instead of relying on the plugin directory.

Thanks!

**Comment by evansims** [comment]
Hi @star26bsd 👋 Thanks for your feedback!

We don't currently offer the plugin in a packaged form that will work without using Composer, and our guidance is to install it using Composer from within your WordPress installation's plugin folder using `composer install auth0/wordpress`.

We're also still ironing out some details on the transition process from plugin V4 to V5, which is why we haven't fully rolled v5 out to the Plugin Directory quite yet, but it should show up there in a few weeks time. Thanks for your patience!

On both accounts I've noted your feedback and totally agree those need resolved; we're working on it 👍
