### ISSUE TITLE
Unable to build the latest version of the Auth0 Wordpress plugin - please provide details on how to do this.

### ISSUE THREAD

**Issue by steve-dolha** [auth0/wordpress#863]
### Describe the problem

I've cloned the source for the Auth0 wordpress plugin from Github and installed the required libraries using Composer, but there are no clear instructions on how to build the actual Wordpress plugin that can be installed into Wordpress version 6 (the current version on the Wordpress site does not work with version 6 and notes indicate that the latest source on Github does resolve this issue). 

### What was the expected behavior?
Need instructions on how to build the Auth0 Wordpress plugin in the correct format for installing to a version 6 wordpress installation. The current source on Github does not include this.
### Reproduction
Steps I tried to get the latest version of the Auth0 Wordpress plugin ready to install into a Wordpress site:
- Clone Github auth0/wordpress
- Run composer to install dependencies
- Not clear what next steps are to build the actual Wordpress plugin zip file structure.
### Environment
- Latest version on Github auth0/wordpress respository

**Comment by steve-dolha** [comment]
If you can provide a packaged build of version 5.0.1 of the plugin as a download that would work as well.

**Comment by evansims** [comment]
Hi @steve-dolha 👋 There's no build process necessary, really. You can run `composer require auth0/wordpress` from your `wp-content` directory to install the plugin and necessary dependencies. However, an updated version of the plugin will be landing on the WordPress store in the next few weeks as well.

**Comment by blakmarkit** [comment]
Momentarily reviving a closed thread. 

@evansims I know that dev timelines slip, but it's been well over a year since your last post and there still isn't a package on the WP repository nor here on GitHub. I've counted many issues raised here over the last few years related to PHP 8+ and WP 6+ support, all closed with no release as a true resolution.

I have tried the composer installation—something is wrong with the documented instructions. I've already been using composer to manage dependencies for my sites with wpackagist, but I'm not using Bedrock. I'm getting a fatal error upon activation. I don't know if it has anything to do with previously having 4.x installed. Not having a baseline zip or WP plugin repo option after 17 months of 5.x being available is kind of wild. I **have** to get this working. Rolling back WP or PHP are not viable options. Continuing to use 4.x is not an option.
